// Generated by app/gen_voice_phrases.py from app/voice.py - do not edit by hand.
#pragma once

struct VoicePhraseGroup {
	const char *cmd;
	const char *title;
	const char *what;
	const char *gate;
	const char *phrases; // separated by |
};

static const VoicePhraseGroup kVoicePhrases[] = {
	{"replay", "Instant replay", "plays the last highlight", "Kennel - instant replay",
	 "replay|instant replay|play that back|play it back|run it back|play it again|rewind|show the replay|replay that"},
	{"clip", "Clip that", "saves a clip; the sentence after it becomes the title", "Kennel - clip that",
	 "clip|clip that|clip it|clip this|save that|save clip|save the clip|record that|clip him|clip the last bit"},
	{"clip_replay", "Clip replay", "saves a clip and plays it back at once", "Kennel - clip that + instant replay",
	 "clip replay|clip and replay|clip then replay|clip that and replay|save and replay|clip it and replay|replay clip|clip and play it back"},
	{"dual", "Dual POV on", "the small second-POV window", "Kennel - force dual point of view",
	 "dual|dual pov|dual point of view|force dual|split screen|both povs|two povs|dual on|go dual"},
	{"dual_off", "Dual POV off", "", "Kennel - force dual point of view",
	 "dual off|dual pov off|stop dual|single pov|end dual|turn off dual"},
	{"force", "Squad mate POV", "the chosen squad mate on stream now, downed or not",
	 "Kennel - force squad mate point of view",
	 "force squad mate|force squad mate pov|squad mate pov|show squad mate|show my squad mate|show his pov|show her pov|show their pov|teammate pov|switch to squad mate|squad mate point of view|show squad mate point of view|go to squad mate"},
	{"change", "Change squad mate",
	 "the next one with a picture, or by name: \"show bouga\", \"switch to carranco\"",
	 "Kennel - change squad mate point of view",
	 "change squad mate|next squad mate|switch squad mate|other squad mate|next pov|change pov|change point of view|swap squad mate|next one|someone else|change squad mate point of view|show <name>|switch to <name>|put <name> on"},
	{"closest", "Closest squad mate", "the nearest one from the NEARBY list",
	 "Kennel - show closest squad mate point of view",
	 "closest|nearest|show closest|closest squad mate|nearest squad mate|who is closest|whos closest|show the closest pov|closest pov|nearest pov|show closest squad mate point of view"},
	{"me", "Back to me", "your own POV", "always on",
	 "back|my pov|me|back to me|my point of view|show me|stop|my screen|go back|back to my pov"},
	{"highlights", "Highlights", "plays the compilation of this stream's highlights", "always on",
	 "highlights|play highlights|compilation|montage|play the compilation"},
};
